import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideBar from "@/components/sidebar";
import { ModalProvider } from "@/context/ModalContext";
import SideBarWrapper from "@/components/sideBarWrapper";
import { AuthProvider } from "@/context/AuthContext";
import { TaskProvider } from "@/context/TaskContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex antialiased">
        <AuthProvider>
          <ModalProvider>
            <TaskProvider>
              <SideBarWrapper />
              {children}
            </TaskProvider>
          </ModalProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
