export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayOut({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className="w-full">{children}</div>;
}
