// import type { Metadata } from "next";
// import { ModalProvider } from "@/context/ModalContext";
// import SideBarWrapper from "@/components/sideBarWrapper";
// import { AuthProvider } from "@/context/AuthContext";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function DashBoardLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <main className="flex w-full">
//       <AuthProvider>
//         <ModalProvider>
//           <SideBarWrapper />
//           {children}
//         </ModalProvider>
//       </AuthProvider>
//     </main>
//   );
// }
